baseURL = 'https://ailyz.com/'
languageCode = 'en-us'
title = 'Ailyz'

[menus]
  [[menus.main]]
  name = 'Contact'
  url = '/pages/contact-us/'
  weight = 1

  [[menus.main]]
  name = 'AI blog'
  url = '/blogs/ai/'
  weight = 2

[params]
  description = 'Ailyz is a customer service system that is specifically made for Shopify stores.'
